before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm
      - arm64
      - mipsle
      - mips
      - 386
    gomips:
      - hardfloat
      - softfloat
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
        goarm: 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: mosdns-archive
    builds:
      - mosdns-cn
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}-{{ .Arm }}{{ end }}{{ if .Mips }}-{{ .Mips }}{{ end }}"
    format: zip
changelog:
  skip: true

snapshot:
  name_template: "{{ .Tag }}-next"

